##########################################################################################
# MiPush Zygisk Magisk installer
##########################################################################################

SKIPMOUNT=false
PROPFILE=false
POSTFSDATA=false
LATESTARTSERVICE=false

CONFIG_DIR=/data/adb/mipush_zygisk
CONFIG_FILE=$CONFIG_DIR/app.conf
DEVICE_CONFIG_FILE=$CONFIG_DIR/device.conf
MIPUSHCUT_TARGET=/product/app/split-XiaomiServiceFrameworkCN
MIPUSHCUT_STATE_FILE=$CONFIG_DIR/mipushcut.state
PREVIOUS_MIPUSHCUT_REPLACE=false
REPLACE=''
MIPUSHCUT_HELPER_TEMP=''

mipushcut_load_guard() {
  if [ -r "${TMPDIR:-}/mipushcut_guard.sh" ]; then
    . "$TMPDIR/mipushcut_guard.sh"
    return 0
  fi
  if [ -r "${MODPATH:-}/mipushcut_guard.sh" ]; then
    . "$MODPATH/mipushcut_guard.sh"
    return 0
  fi
  if [ -z "${ZIPFILE:-}" ]; then
    return 1
  fi

  MIPUSHCUT_HELPER_TEMP="${TMPDIR:-/data/local/tmp}/mipushcut_guard.$$"
  mkdir -p "${MIPUSHCUT_HELPER_TEMP%/*}" 2>/dev/null || return 1
  if ! unzip -p "$ZIPFILE" mipushcut_guard.sh > "$MIPUSHCUT_HELPER_TEMP" 2>/dev/null; then
    MIPUSHCUT_HELPER_TEMP=''
    return 1
  fi
  . "$MIPUSHCUT_HELPER_TEMP"
}

# Older module releases installed a complete MIUI 14-era device.conf. It was
# generated by the module itself, so migrate that known default; user-edited
# configs are left untouched and remain explicit overrides.
migrate_legacy_device_config() {
  if [ ! -f "$DEVICE_CONFIG_FILE" ]; then
    return
  fi
  if grep -q '^# MiPush Zygisk device spoof config$' "$DEVICE_CONFIG_FILE" \
    && grep -q '^ro.miui.ui.version.name=V130$' "$DEVICE_CONFIG_FILE" \
    && grep -q '^ro.build.version.release=12$' "$DEVICE_CONFIG_FILE"; then
    cp "$DEFAULT_DEVICE_CONFIG" "$DEVICE_CONFIG_FILE"
    chmod 600 "$DEVICE_CONFIG_FILE"
    ui_print "- Migrated legacy device profile to built-in profile defaults"
  fi
}

print_modname() {
  ui_print "*******************************"
  ui_print " MiPush Zygisk + Xiaomi Service Framework "
  ui_print "*******************************"
}

on_install() {
  DEFAULT_CONFIG=$MODPATH/defaults/app.conf
  DEFAULT_DEVICE_CONFIG=$MODPATH/defaults/device.conf
  ui_print "- Extracting MiPush Zygisk files"

  if ! mipushcut_load_guard; then
    mipushcut_should_enable_with_state() { return 1; }
    mipushcut_save_state() { return 1; }
    mipushcut_has_replace_marker() { return 1; }
  fi

  for previous_module_path in \
    "/data/adb/modules/mipush_zygisk" \
    "/data/adb/modules_update/mipush_zygisk"; do
    [ "$previous_module_path" = "${MODPATH:-}" ] && continue
    if mipushcut_has_replace_marker "$previous_module_path"; then
      PREVIOUS_MIPUSHCUT_REPLACE=true
      break
    fi
  done

  if mipushcut_should_enable_with_state \
    "$MIPUSHCUT_TARGET" "$MIPUSHCUT_STATE_FILE" "$PREVIOUS_MIPUSHCUT_REPLACE"; then
    REPLACE="$MIPUSHCUT_TARGET"
    mipushcut_save_state "$MIPUSHCUT_STATE_FILE" enabled || \
      ui_print "- Warning: could not persist MiPushCut enabled state"
    ui_print "- Stock XMSF path/APK or previous state detected; enabling MiPushCut: $MIPUSHCUT_TARGET"
    # Keep the native system overlay and marker. Do not add a second bind mount.
    unzip -o "$ZIPFILE" 'defaults/*' 'bin/*' 'zygisk/*' 'system/*' -d "$MODPATH" >&2
  else
    REPLACE=''
    mipushcut_save_state "$MIPUSHCUT_STATE_FILE" disabled || \
      ui_print "- Warning: could not persist MiPushCut disabled state"
    ui_print "- MiPushCut skipped: stock XMSF path/APK unavailable"
    # Zygisk and configuration files remain installed; no system replacement is extracted.
    unzip -o "$ZIPFILE" 'defaults/*' 'bin/*' 'zygisk/*' -d "$MODPATH" >&2
  fi

  for target in $REPLACE; do
    ui_print "- Hiding Xiaomi Service Framework: $target"
  done

  mkdir -p "$CONFIG_DIR"
  chmod 700 "$CONFIG_DIR"
  if [ ! -f "$CONFIG_FILE" ] && [ -f "$DEFAULT_CONFIG" ]; then
    cp "$DEFAULT_CONFIG" "$CONFIG_FILE"
    chmod 600 "$CONFIG_FILE"
  fi
  if [ ! -f "$DEVICE_CONFIG_FILE" ] && [ -f "$DEFAULT_DEVICE_CONFIG" ]; then
    cp "$DEFAULT_DEVICE_CONFIG" "$DEVICE_CONFIG_FILE"
    chmod 600 "$DEVICE_CONFIG_FILE"
  fi
  migrate_legacy_device_config

  if [ -n "$MIPUSHCUT_HELPER_TEMP" ]; then
    rm -f "$MIPUSHCUT_HELPER_TEMP"
  fi
}

set_permissions() {
  set_perm_recursive "$MODPATH" 0 0 0755 0644
  set_perm "$MODPATH/bin/mipushctl" 0 0 0755
}
