##########################################################################################
# MiPush Zygisk Magisk installer
##########################################################################################

SKIPMOUNT=false
PROPFILE=false
POSTFSDATA=false
LATESTARTSERVICE=true

CONFIG_DIR=/data/adb/mipush_zygisk
CONFIG_FILE=$CONFIG_DIR/app.conf
DEVICE_CONFIG_FILE=$CONFIG_DIR/device.conf
MIPUSHCUT_TARGET=/product/app/split-XiaomiServiceFrameworkCN
MIPUSHCUT_STATE_FILE=$CONFIG_DIR/mipushcut.state
PREVIOUS_MIPUSHCUT_REPLACE=false
REPLACE=''
MIPUSHCUT_HELPER_TEMP=''

mipushcut_load_guard() {
  if [ -r "${TMPDIR:-}/mipushcut_guard.sh" ]; then
    . "$TMPDIR/mipushcut_guard.sh"
    return 0
  fi
  if [ -r "${MODPATH:-}/mipushcut_guard.sh" ]; then
    . "$MODPATH/mipushcut_guard.sh"
    return 0
  fi
  if [ -z "${ZIPFILE:-}" ]; then
    return 1
  fi

  MIPUSHCUT_HELPER_TEMP="${TMPDIR:-/data/local/tmp}/mipushcut_guard.$$"
  mkdir -p "${MIPUSHCUT_HELPER_TEMP%/*}" 2>/dev/null || return 1
  if ! unzip -p "$ZIPFILE" mipushcut_guard.sh > "$MIPUSHCUT_HELPER_TEMP" 2>/dev/null; then
    MIPUSHCUT_HELPER_TEMP=''
    return 1
  fi
  . "$MIPUSHCUT_HELPER_TEMP"
}

# Older module releases installed a complete MIUI 14-era device.conf. It was
# generated by the module itself, so migrate that known default; user-edited
# configs are left untouched and remain explicit overrides.
migrate_legacy_device_config() {
  if [ ! -f "$DEVICE_CONFIG_FILE" ]; then
    return
  fi
  if grep -q '^# MiPush Zygisk device spoof config$' "$DEVICE_CONFIG_FILE" \
    && grep -q '^ro.miui.ui.version.name=V130$' "$DEVICE_CONFIG_FILE" \
    && grep -q '^ro.build.version.release=12$' "$DEVICE_CONFIG_FILE"; then
    cp "$DEFAULT_DEVICE_CONFIG" "$DEVICE_CONFIG_FILE"
    chmod 600 "$DEVICE_CONFIG_FILE"
    ui_print "- Migrated legacy device profile to built-in profile defaults"
  fi
}

print_modname() {
  ui_print "*******************************"
  ui_print " MiPush Zygisk + Xiaomi Service Framework "
  ui_print "*******************************"
}

on_install() {
  DEFAULT_CONFIG=$MODPATH/defaults/app.conf
  DEFAULT_DEVICE_CONFIG=$MODPATH/defaults/device.conf
  ui_print "- Extracting MiPush Zygisk files"

  if ! mipushcut_load_guard; then
    mipushcut_should_enable_with_state() { return 1; }
    mipushcut_save_state() { return 1; }
    mipushcut_has_replace_marker() { return 1; }
    mipushcut_choose_mode() { MIPUSH_SELECTED_MODE=both; }
    mipushcut_systemui_shared_uid1000() { return 1; }
    mipushcut_confirm() { return 1; }
    mipushcut_write_spoof_state() { return 0; }
  fi
  mipushcut_start_listener 2>/dev/null || true
  mipushcut_start_listener 2>/dev/null || true

  # The picker sets MIPUSH_SELECTED_MODE globally: command substitution does
  # not reliably capture function stdout in the KSU installer environment.
  mipushcut_choose_mode "$MIPUSHCUT_STATE_FILE" "$CONFIG_FILE"
  MODE=$MIPUSH_SELECTED_MODE
  MIPUSHCUT_WANTED=false
  case "$MODE" in cut|both) MIPUSHCUT_WANTED=true ;; esac

  for previous_module_path in \
    "/data/adb/modules/mipush_zygisk" \
    "/data/adb/modules_update/mipush_zygisk"; do
    [ "$previous_module_path" = "${MODPATH:-}" ] && continue
    if mipushcut_has_replace_marker "$previous_module_path"; then
      PREVIOUS_MIPUSHCUT_REPLACE=true
      break
    fi
  done

  if [ "$MIPUSHCUT_WANTED" = true ]; then
    if ! mipushcut_should_enable_with_state \
      "$MIPUSHCUT_TARGET" "$MIPUSHCUT_STATE_FILE" "$PREVIOUS_MIPUSHCUT_REPLACE"; then
      ui_print "- MiPushCut 跳过: stock XMSF 路径/APK 不存在 / skipped: stock XMSF path unavailable"
      MIPUSHCUT_WANTED=false
    elif mipushcut_systemui_shared_uid1000; then
      # Safety gate: on ROMs where SystemUI shares uid 1000 with stock XMSF
      # (older MIUI/HyperOS ports), hiding the platform-signed stock package can
      # flip the shared user's seinfo and crash-loop SystemUI. Require explicit
      # consent; unattended installs skip MiPushCut instead.
      ui_print "! 警告: 此 ROM 的 SystemUI 与 stock XMSF 同在 uid 1000 共享用户 / WARNING: SystemUI shares the uid 1000 shared user."
      ui_print "! 隐藏 stock XMSF 可能翻转共享用户 seinfo 并导致 SystemUI 崩溃 / hiding stock XMSF may crash SystemUI."
      if mipushcut_confirm 15; then
        ui_print "! 已按要求启用 MiPushCut; 若 SystemUI seinfo 翻转, 开机自愈将自动禁用 / enabled at your request; boot self-heal will auto-disable it."
      else
        ui_print "- 共享组安全门禁拦截, MiPushCut 已跳过 (伪装仍生效) / skipped by the shared-uid safety gate"
        MIPUSHCUT_WANTED=false
      fi
    fi
  fi

  if [ "$MIPUSHCUT_WANTED" = true ]; then
    REPLACE="$MIPUSHCUT_TARGET"
    mipushcut_save_state "$MIPUSHCUT_STATE_FILE" enabled || \
      ui_print "- Warning: could not persist MiPushCut enabled state"
    ui_print "- MiPushCut 已启用 (检测到 stock XMSF 或沿用先前状态) / enabled: $MIPUSHCUT_TARGET"
    # Keep the native system overlay and marker. Do not add a second bind mount.
    unzip -o "$ZIPFILE" 'defaults/*' 'bin/*' 'zygisk/*' 'system/*' -d "$MODPATH" >&2
  else
    REPLACE=''
    mipushcut_save_state "$MIPUSHCUT_STATE_FILE" disabled || \
      ui_print "- Warning: could not persist MiPushCut disabled state"
    if [ "$MODE" = spoof ]; then
      ui_print "- 只伪装模式: stock XMSF 未改动 / spoof-only: stock XMSF untouched"
    else
      ui_print "- MiPushCut 跳过: stock XMSF 不可用或未确认 / skipped: unavailable or declined"
    fi
    # Zygisk and configuration files remain installed; no system replacement is extracted.
    unzip -o "$ZIPFILE" 'defaults/*' 'bin/*' 'zygisk/*' -d "$MODPATH" >&2
  fi

  for target in $REPLACE; do
    ui_print "- Hiding Xiaomi Service Framework: $target"
  done

  mkdir -p "$CONFIG_DIR"
  chmod 700 "$CONFIG_DIR"
  if [ ! -f "$CONFIG_FILE" ] && [ -f "$DEFAULT_CONFIG" ]; then
    cp "$DEFAULT_CONFIG" "$CONFIG_FILE"
    chmod 600 "$CONFIG_FILE"
  fi
  if [ ! -f "$DEVICE_CONFIG_FILE" ] && [ -f "$DEFAULT_DEVICE_CONFIG" ]; then
    cp "$DEFAULT_DEVICE_CONFIG" "$DEVICE_CONFIG_FILE"
    chmod 600 "$DEVICE_CONFIG_FILE"
  fi
  migrate_legacy_device_config

  # Spoof master switch follows the selected mode; cut-only disables spoofing.
  case "$MODE" in
    cut) mipushcut_write_spoof_state "$CONFIG_FILE" off || \
      ui_print "- Warning: could not persist spoof=off" ;;
    *) mipushcut_write_spoof_state "$CONFIG_FILE" on || \
      ui_print "- Warning: could not persist spoof=on" ;;
  esac

  if [ -n "$MIPUSHCUT_HELPER_TEMP" ]; then
    rm -f "$MIPUSHCUT_HELPER_TEMP"
  fi
}

set_permissions() {
  set_perm_recursive "$MODPATH" 0 0 0755 0644
  set_perm "$MODPATH/bin/mipushctl" 0 0 0755
}
